# Generated by Django 2.1.3 on 2018-11-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(default='', max_length=90),
        ),
    ]
