# Generated by Django 2.1.3 on 2018-11-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_question_text_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='option2_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='option3_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='option4_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
